### ISSUE TITLE
Which IMDB example to start with

### ISSUE THREAD

**Issue by KvEijden** [msdslab/systematic-reviews#11]
On the keras website https://keras.rstudio.com/articles/examples/index.html there are several examples with the imdb dataset. There is also another one on https://tensorflow.rstudio.com/blog/text-classification-with-keras.html.

The one we started with last Thursday was the lstm model. But we didn't discuss if that was the right choice?

**Comment by daob** [comment]
Yes, LSTM-imdb https://github.com/rstudio/keras/blob/master/vignettes/examples/imdb_lstm.R
