### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by KvEijden** [msdslab/systematic-reviews#6]
The ID's in the data files don't match.
The same articles don't have the same ID in the different files

**Comment by daob** [comment]
"ID" here is probably just an arbitrary number corresponding to count in the endnote file. Titles should match exactly?

**Comment by daob** [comment]
There are more problems with the data. Kees is working with Rens to solve them.

**Comment by daob** [comment]
Closed after conferring with Rens. Some errors in data munging and 3 additional papers after Scopus changed the database retrospectively explained this.
